services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: laravel-backend
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./backend:/var/www
        depends_on:
            - redis
        networks:
            - app-network 

    frontend: 
        build: 
          context: ./frontend
          dockerfile: Dockerfile
        container_name: vue-frontend
        restart: unless-stopped
        working_dir: /app
        ports:
          - "5173:5173"
        volumes:
            - ./frontend:/app
            - /app/node_modules 
        networks:
            - app-network
        
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - ./backend:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - app-network 

    db:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE:-laravel}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
            MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
            MYSQL_USER: ${DB_USERNAME:-username}
        volumes:
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports:
            - "3388:3306"
        networks:
            - app-network 

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        env_file:
            - ./backend/.env
        ports:
            - "8989:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-userpass}
        networks:
            - app-network 

    redis:
        image: redis:latest
        networks:
            - app-network 

networks:
    app-network:
        driver: bridge